name: build-test-deploy2
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repository code
        uses: actions/checkout@v3
      - name: use node.js20
        uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build
  test: 
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js20
        uses: actions/setup-node@v3
      - run: npm install
      - run: npm test
      
